version: '3'

volumes:
  postgres_data:
    driver: local

services:
  go_db:
    image: postgres
    container_name: go_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog_app
      POSTGRES_USER: amir
      POSTGRES_PASSWORD: amir
  go_app:
    container_name: go_app
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8002:8002
    depends_on:
      - go_db
networks: 
  default: 
    external: 
      name: ABCNetworkGo